# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f788cf4251cf37f2435d19157bf764f090a784dfa21e87b83f4200a2e3fe1e0a2c86df7e57b80ba10177b2ebbf79e38694ef98fc89c64efa07f386047eb1cda

test:
  secret_key_base: 1726dd92ff7d54ec25eed50fe26f9b5e5c6a4855fa3ba2784553c3e22e6b357e3675846106b5733c2a9d93775f4266c70a7dd0a7bf4fbb89763ca5e25e54b174

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
